services:
  web:
    build: .
    container_name: spongebob_backend
    env_file:
      - postgres.env
    environment:
      - DB_URL=${POSTGRES_URL}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}

    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgres_db
    env_file:
      - postgres.env
    image: postgres
    volumes:
      - .db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB};"]
      interval: 1s
volumes:
  db-data:
